{% set name = "pyjsg" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 88cc9ad6b9835cbcca6255b938a43205cbc8e2656a570dec51936b1ca6005092

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  entry_points:
    - generate_parser = pyjsg.parser_impl.generate_python:generate

requirements:
  host:
    - python {{ python_min }}
    - pbr
    - pip
  run:
    - python >={{ python_min }}
    - antlr4-python3-runtime >=4.9.3,<4.10.dev0
    - jsonasobj >=1.2.1

test:
  imports:
    - pyjsg
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/hsolbrig/pyjsg
  summary: Python JSON Schema Grammar interpreter
  license: CC0-1.0
  license_file: license.txt

extra:
  recipe-maintainers:
    - jfy133
