# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.12.4"
  python_check_max: "3.14"

package:
  name: pyjsg
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/p/pyjsg/pyjsg-${{ version }}.tar.gz
  sha256: bb1c0ff1f50846d2b5185b182e28b0b6978eae51a2078ce3eb1e0f28dea7b9ab

build:
  number: 0
  noarch: python
  python:
    entry_points:
      - generate_parser = pyjsg.parser_impl.generate_python:generate
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check --check-build-dependencies

requirements:
  host:
    - hatchling
    - pip
    - python ${{ python_min }}.*
    - uv-dynamic-versioning
  run:
    - antlr4-python3-runtime >=4.9.3,<4.10.dev0
    - jsonasobj >=1.2.1
    - python >=${{ python_min }}
    - requests

tests:
  - package_contents:
      strict: true
      site_packages:
        - pyjsg/**
        - pyjsg-${{ version }}.dist-info/**
  - python:
      imports: pyjsg
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - ${{ python_check_max }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - generate_parser --help

about:
  summary: Python JSON Schema Grammar interpreter
  license: CC0-1.0
  license_file: license.txt
  homepage: https://pypi.org/project/pyjsg
  repository: https://github.com/linkml/pyjsg

extra:
  recipe-maintainers:
    - bollwyvl
